const list = [
  "Air-conditioning",
  "Bathrobes and slippers",
  "Bike and car rental",
  "Breakfast buffet",
  "Daily newspapers",
  "Direct dial telephone",
  "Dry cleaning service",
  "Exclusive luxury L'Occitane toiletries",
  "Family / adjoining rooms (on request)",
  "Flat screen satellite TV",
  "Free wifi",
  "Garden",
  "Laundry service",
  "Luggage trolley",
  "Mini bar",
  "Pay-per-view TV channels",
  "Safety deposit box (free of charge)",
  "24 hour room service",
];
export default list;
